# Generated by Django 4.2.25 on 2025-12-28 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pre_prompt', models.TextField(default='You are an ai who help user.')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='avatar_pics')),
                ('cooldown', models.IntegerField(default=5)),
                ('model_type', models.CharField(choices=[('LOCAL', 'Local'), ('API', 'API')], default='API', max_length=10)),
                ('conversation', models.TextField(blank=True, default='')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_message_date', models.DateTimeField(auto_now=True)),
                ('interaction_count', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
